//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NotifyServer.Models
{
    using OlympicMedalListApp;
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using Xamarin.Forms;

    public partial class Athlete
    {
    
        public int ID { get; set; }
        public string Name { get; set; }
        public bool Sex { get; set; }
        public System.DateTime Birthdate { get; set; }
        public int CountryID { get; set; }
        public string Portrait { get; set; }
        public byte[] PortraitImg { get; set; }

        public virtual Country Country { get; set; }
        public virtual ICollection<MedalList> MedalLists { get; set; }

        public ImageSource PortraitImageSource => ImageSource.FromStream(()=> { return new MemoryStream(PortraitImg); });
        public int No { get; set; }
        public int GoldNumber => App.MedalList.Count(a=>a.AthleteID == ID && a.MedalType == 1);
        public int SilverNumber => App.MedalList.Count(a=>a.AthleteID == ID && a.MedalType == 2);
        public int BronzeNumber => App.MedalList.Count(a=>a.AthleteID == ID && a.MedalType == 3);
        public int TotalMedalNumber => GoldNumber + SilverNumber + BronzeNumber;

        public Color RankColor => No <= 3 ? (No == 1 ? Color.Red : (No == 2 ? Color.Orange : Color.Yellow)) : Color.White;
        public int RankSize => No <= 3 ? (No == 1 ? 26 : (No == 2 ? 22 : 18)) : 16;

    }
}
