//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NotifyServer.Models
{
    using OlympicMedalListApp;
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using Xamarin.Forms;

    public partial class Country
    {
    
        public int ID { get; set; }
        public string Name { get; set; }
        public string Flag { get; set; }
        public byte[] FlagImg { get; set; }

        public ImageSource FlagImageSource => ImageSource.FromStream(() =>
        {
            return new MemoryStream(FlagImg);
            //using (MemoryStream ms = new MemoryStream(FlagImg))
            //{
            //    return ms;
            //}
        });

        public int No { get; set; }

        public int GoldNumber => App.MedalList.Count(x => x.MedalType == 1 && x.Athlete.CountryID == ID);
        public int SilverNumber => App.MedalList.Count(x => x.MedalType == 2 && x.Athlete.CountryID == ID);
        public int BronzeNumber => App.MedalList.Count(x => x.MedalType == 3 && x.Athlete.CountryID == ID);
        public int TotalMedalNumber => GoldNumber + SilverNumber + BronzeNumber;

        public Color RankColor => No <= 3 ? (No == 1 ? Color.Red : (No == 2 ? Color.Orange : Color.Yellow)) : Color.White;
        public int RankSize => No <= 3 ? (No == 1 ? 26 : (No == 2 ? 22 : 18)) : 16;

        public virtual ICollection<Athlete> Athletes { get; set; }
    }
}
